<a href="https://colab.research.google.com/github/neelkothimbire/PyTorch/blob/main/PyTorch_Training_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [37]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [38]:
df.shape

(569, 33)

In [39]:
df.drop(columns=['id','Unnamed: 32'] , inplace=True)

In [40]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## train test split

In [41]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:] , df.iloc[:,0] ,test_size=0.2)

##scaling

In [42]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [43]:
X_train

array([[ 0.18386344,  0.53787138,  0.16515466, ...,  1.07075162,
         1.32101123,  1.38909215],
       [ 1.61343623,  1.36306371,  1.58425959, ...,  0.91665295,
         0.676324  ,  0.03157858],
       [-0.53373706, -0.29433393, -0.53767894, ..., -0.84037401,
        -0.79841853, -0.37211031],
       ...,
       [ 0.26547291, -0.88342308,  0.24252337, ...,  0.3833507 ,
         0.10053465, -0.02491593],
       [-0.98118209,  0.21761259, -0.86914276, ...,  0.51327703,
        -0.48509726,  1.9704919 ],
       [-0.24951098,  0.58929979, -0.24734269, ...,  0.72780655,
         1.3128091 ,  0.66398793]])

In [44]:
y_train

57     M
129    M
480    B
115    B
538    B
      ..
477    B
355    B
227    B
376    B
44     M
Name: diagnosis, Length: 455, dtype: object

## Label Encoding

In [45]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.fit_transform(y_test)

In [46]:
y_train

array([1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,

## Numpy arrays to Pytorch tensors

In [47]:
X_train_tensors=torch.from_numpy(X_train)
X_test_tensors=torch.from_numpy(X_test)
y_train_tensors=torch.from_numpy(y_train)
y_test_tensors=torch.from_numpy(y_test)

In [48]:
X_train_tensors.shape

torch.Size([455, 30])

In [49]:
y_train_tensors.shape

torch.Size([455])

## Defining the model

In [55]:
class mySimpleNN():
  def __init__(self,x):
    self.weights=torch.rand(x.shape[1],1,dtype=torch.float64 , requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float32,requires_grad=True)

  def forward(self,x):
    z=torch.matmul(x,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensors * torch.log(y_pred) + (1 - y_train_tensors) * torch.log(1 - y_pred)).mean()
    return loss


## Imprtant parameters

In [51]:
learning_rate=0.1
epochs=25

## Training Pipeline

In [56]:
#create model
model=mySimpleNN(X_train_tensors)

#define loop
for epoch in range(epochs):

  #forward pass
  y_pred=model.forward(X_train_tensors)

  #loss
  loss=model.loss_function(y_pred,y_train_tensors)

  #backward pass
  loss.backward()

  #parameters update
  with torch.no_grad():
    model.weights -= learning_rate*model.weights.grad
    model.bias -= learning_rate*model.bias.grad

  #zero grad
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f'Epoch : {epoch+1} , Loss:{loss.item()}')


Epoch : 1 , Loss:3.5406807119306065
Epoch : 2 , Loss:3.411780536376057
Epoch : 3 , Loss:3.2807324571951653
Epoch : 4 , Loss:3.1459919525893696
Epoch : 5 , Loss:3.010675494025676
Epoch : 6 , Loss:2.8687987005300477
Epoch : 7 , Loss:2.7225704056940963
Epoch : 8 , Loss:2.576425980329264
Epoch : 9 , Loss:2.423653883600633
Epoch : 10 , Loss:2.260915074412958
Epoch : 11 , Loss:2.0956668465790393
Epoch : 12 , Loss:1.933217676921674
Epoch : 13 , Loss:1.7783538207175025
Epoch : 14 , Loss:1.6259359245761085
Epoch : 15 , Loss:1.4844281963670085
Epoch : 16 , Loss:1.3541621835285367
Epoch : 17 , Loss:1.2398309374026502
Epoch : 18 , Loss:1.1418616838822797
Epoch : 19 , Loss:1.0600638332050265
Epoch : 20 , Loss:0.9935150358997796
Epoch : 21 , Loss:0.9403447992741566
Epoch : 22 , Loss:0.8982447165455558
Epoch : 23 , Loss:0.8650195730534692
Epoch : 24 , Loss:0.8387664113460404
Epoch : 25 , Loss:0.8179049472631037


In [57]:
model.weights

tensor([[-0.2065],
        [ 0.3556],
        [ 0.4243],
        [ 0.5999],
        [-0.2695],
        [-0.0351],
        [ 0.0834],
        [ 0.2038],
        [ 0.4739],
        [ 0.5450],
        [-0.2827],
        [ 0.4390],
        [-0.3104],
        [-0.2473],
        [-0.0128],
        [ 0.1581],
        [ 0.1355],
        [ 0.0584],
        [ 0.1330],
        [-0.3502],
        [-0.3040],
        [-0.1109],
        [-0.1223],
        [ 0.4977],
        [ 0.0997],
        [-0.2110],
        [-0.4459],
        [-0.3847],
        [ 0.3194],
        [ 0.3882]], dtype=torch.float64, requires_grad=True)

In [58]:
model.bias

tensor([-0.1520], requires_grad=True)

## Evaluation

In [62]:
with torch.no_grad():
  y_pred=model.forward(X_test_tensors)
  y_pred = (y_pred >0.5).float()
  accuracy = (y_pred == y_test_tensors).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5221606492996216
