<a href="https://colab.research.google.com/github/neelkothimbire/PyTorch/blob/main/Tensors_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing



In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
    print("GPU is available")
    print("GPU name: ", torch.cuda.get_device_name(0))
    print("GPU memory: ", torch.cuda.get_device_properties(0).total_memory)
else:
    print("GPU  is not available , using CPU")

GPU is available
GPU name:  Tesla T4
GPU memory:  15828320256


## Creating a Tensor

In [ ]:
#using empty
a=torch.empty(2,3)

In [ ]:
#check type
type(a)

torch.Tensor

In [ ]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2,3)

tensor([[0.5947, 0.5808, 0.5795],
        [0.9419, 0.6055, 0.7888]])

In [ ]:
#use of seed (for using reporduce)
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#other ways

#arange
print("using arrange -> " , torch.arange(0,10,2))

# using linspace (evenly placed)
print("using linspace -> ", torch.linspace(0,10,10))

#using eye (identity matrix)
print("using eye ->", torch.eye(5))

#using full
print("using full -> ", torch.full((3,3),5))

using arrange ->  tensor([0, 2, 4, 6, 8])
using linspace ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [ ]:
#if you want to create a shape of tensor but using same shape of other tensor
torch.empty_like(x)

tensor([[ 815964940,          0,          0],
        [1065353216,          0,          0]])

In [ ]:
#another
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x , dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Datatypes

In [ ]:
#find datatype
x.dtype

torch.int64

In [ ]:
#assign datatype
torch.tensor([[1,2,3],[4,5,6]], dtype=torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float32)

tensor([1., 2., 3.])

In [ ]:
# to change datatype of existing tensor
x.to(torch.float32)


tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


##Mathematical Operations


### 1.Scalar Operations

In [ ]:
x=torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
#addition
x+2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [ ]:
#subtraction
x-2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [ ]:
#multiplicaiton
x*3

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [ ]:
#division
x/4

tensor([[0.1779, 0.1969],
        [0.1046, 0.2254]])

In [ ]:
#int division
(x*100)//2

tensor([[35., 39.],
        [20., 45.]])

In [ ]:
# mod
((x*100)//2)%2

tensor([[1., 1.],
        [0., 1.]])

In [ ]:
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

### 2. Element wise Operation

In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [ ]:
#add
a+b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [ ]:
#sub
a-b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [ ]:
#multi
a*b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [ ]:
#div
a/b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [ ]:
#power
a**b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [ ]:
#mod
a%b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

### other operations

In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
#round
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
#cell
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
#clamp  you can keep it in range
torch.clamp(d,min=2 , max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3.Reduction Operations





In [ ]:
e=torch.randint(size=(2,3), low=0 , high=10 , dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [ ]:
#sum
torch.sum(e)

tensor(24.)

In [ ]:
#sum along col
torch.sum(e,dim=0)

tensor([ 8.,  0., 16.])

In [ ]:
#sum along rows
torch.sum(e,dim=1)

tensor([15.,  9.])

In [ ]:
#mean
torch.mean(e)

#mean aong col
torch.mean(e , dim=0)

#mean aong row
torch.mean(e , dim=1)

tensor([5., 3.])

In [ ]:
#median
torch.median(e)

#median aong col
torch.median(e , dim=0)

#median aong row
torch.median(e , dim=1)

torch.return_types.median(
values=tensor([7., 0.]),
indices=tensor([2, 1]))

In [ ]:
#max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
#product
torch.prod(e)

tensor(0.)

In [ ]:
#standard devation
torch.std(e)

tensor(4.4272)

In [ ]:
#variancr
torch.var(e)

tensor(19.6000)

In [ ]:
#argmax max item position
torch.argmax(e)

tensor(5)

In [ ]:
#arg min min item posiiton
torch.argmin(e)

tensor(1)

### 4 . Matrix Operations

In [ ]:
f=torch.randint(size=(2,3), low=0 , high =10)
g=torch.randint(size=(3,2) , low=0 , high = 10)
print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [ ]:
#matrix multiplication
torch.matmul(f,g)

tensor([[ 87, 119],
        [ 65,  99]])

In [ ]:
# dot product
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

torch.dot(vector1,vector2)

tensor(11)

In [ ]:
#transpose
f
torch.transpose(f,0,1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [ ]:
#detenminant
h=torch.randint(size=(3,3) , low=0 , high =10 , dtype=torch.float32)
print(h)
torch.det(h)

tensor([[7., 8., 3.],
        [6., 1., 5.],
        [5., 0., 4.]])


tensor(21.0000)

In [ ]:
#inverse
torch.inverse(h)

tensor([[ 0.1905, -1.5238,  1.7619],
        [ 0.0476,  0.6190, -0.8095],
        [-0.2381,  1.9048, -1.9524]])

### 5. Comparison Operations

In [ ]:
i=torch.randint(size=(2,3) , low=0 , high=10)
j=torch.randint(size=(2,3), low=0, high=10)
print(i)
print(j)

tensor([[7, 2, 3],
        [8, 5, 6]])
tensor([[2, 9, 5],
        [0, 4, 2]])


In [ ]:
#greater than
i>j

tensor([[ True, False, False],
        [ True,  True,  True]])

In [ ]:
#less than
i<j

tensor([[False,  True,  True],
        [False, False, False]])

In [ ]:
#equal to
i==j

tensor([[False, False, False],
        [False, False, False]])

In [ ]:
#not eqaual to
i!=j

tensor([[True, True, True],
        [True, True, True]])

In [ ]:
#greater than equal to
i>=j

tensor([[ True, False, False],
        [ True,  True,  True]])

In [ ]:
#less than equal
i<=j

tensor([[False,  True,  True],
        [False, False, False]])

### 6 Special Functions

In [ ]:
k=torch.randint(size=(2,3), low=0 , high =10 ,dtype=torch.float32)
k

tensor([[1., 1., 2.],
        [4., 7., 2.]])

In [ ]:
#log
torch.log(k)

tensor([[1.9459, 0.0000, 0.0000],
        [1.6094, 1.3863, 1.3863]])

In [ ]:
#exp
torch.exp(k)

tensor([[1096.6332,    2.7183,    2.7183],
        [ 148.4132,   54.5981,   54.5981]])

In [ ]:
#sqrt
torch.sqrt(k)

tensor([[2.6458, 1.0000, 1.0000],
        [2.2361, 2.0000, 2.0000]])

In [ ]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9991, 0.7311, 0.7311],
        [0.9933, 0.9820, 0.9820]])

In [ ]:
#softmax
torch.softmax(k ,dim=0)

tensor([[0.0474, 0.0025, 0.5000],
        [0.9526, 0.9975, 0.5000]])

In [ ]:
#relu
torch.relu(k)

tensor([[1., 1., 2.],
        [4., 7., 2.]])

## Inplace Operations

In [ ]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.5887, 0.7340, 0.8497],
        [0.9112, 0.4847, 0.9436]])
tensor([[0.3904, 0.2499, 0.3206],
        [0.9753, 0.7582, 0.6688]])


In [ ]:
#inplace operations means without creating a new memory for m+n we store the value(m+n) in M
m.add_(n)

tensor([[0.9792, 0.9839, 1.1703],
        [1.8865, 1.2429, 1.6124]])

In [ ]:
m

tensor([[0.9792, 0.9839, 1.1703],
        [1.8865, 1.2429, 1.6124]])

In [ ]:
n

tensor([[0.3904, 0.2499, 0.3206],
        [0.9753, 0.7582, 0.6688]])

In [ ]:
m.relu_()

tensor([[0.9792, 0.9839, 1.1703],
        [1.8865, 1.2429, 1.6124]])

In [ ]:
m

tensor([[0.9792, 0.9839, 1.1703],
        [1.8865, 1.2429, 1.6124]])

In [ ]:
# take any function and add underscore (_) in front of that so it makes changes n the firstr place  in this case m

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.2651, 0.2336, 0.5057],
        [0.5688, 0.0634, 0.8993]])

In [ ]:
b=a
b #just a refernce function so if you make changes in a then changes will happen in b

tensor([[0.2651, 0.2336, 0.5057],
        [0.5688, 0.0634, 0.8993]])

In [ ]:
a[0][0]=0
a

tensor([[0.0000, 0.2336, 0.5057],
        [0.5688, 0.0634, 0.8993]])

In [ ]:
b

tensor([[0.0000, 0.2336, 0.5057],
        [0.5688, 0.0634, 0.8993]])

In [ ]:
id(a)

138280978075472

In [ ]:
id(b)

138280978075472

In [ ]:
#use clone
b=a.clone()
b

tensor([[10.0000,  0.2336,  0.5057],
        [ 0.5688,  0.0634,  0.8993]])

In [ ]:
a[0][0]=5
a

tensor([[5.0000, 0.2336, 0.5057],
        [0.5688, 0.0634, 0.8993]])

In [ ]:
b

tensor([[10.0000,  0.2336,  0.5057],
        [ 0.5688,  0.0634,  0.8993]])

In [ ]:
id(a)

138280978075472

In [ ]:
id(b)

138280484075280

## Tensor Operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device=torch.device('cuda')

In [ ]:
# creating a new tensor on GPU
torch.rand(2,3 ,device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
#moving an exisitng tensor to GPU
a=torch.rand(2,3)
a

tensor([[0.2732, 0.3397, 0.1879],
        [0.5534, 0.2682, 0.9556]])

In [ ]:
b=a.to(device)
b

tensor([[0.2732, 0.3397, 0.1879],
        [0.5534, 0.2682, 0.9556]], device='cuda:0')

In [ ]:
b+5

tensor([[5.2732, 5.3397, 5.1879],
        [5.5534, 5.2682, 5.9556]], device='cuda:0')

## Reshaping Tensors

In [ ]:
a=torch.ones(4,4)
a
#note to reshape you need to make sure

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [127]:
# flatten  one dimesional tensor
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [128]:
#permute
b=torch.rand(2,3,4)
b

#we permute 2 = 4
# 0=2
# 1=2

tensor([[[0.9761, 0.5934, 0.3124, 0.9431],
         [0.8519, 0.9815, 0.1132, 0.4783],
         [0.4436, 0.3847, 0.4521, 0.5569]],

        [[0.9952, 0.0015, 0.0813, 0.4907],
         [0.2130, 0.4603, 0.1386, 0.0277],
         [0.5662, 0.3503, 0.6555, 0.7667]]])

In [130]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [133]:
#unsqueeze
#image size
#adds new dimesion
c=torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [134]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [135]:
#squeeze
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

## Numpy and Pytorch

In [136]:
import numpy as np

In [139]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [140]:
b=a.numpy()
b

array([1, 2, 3])

In [142]:
type(b)

numpy.ndarray

In [143]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [145]:
d=torch.from_numpy(c)
d

tensor([1, 2, 3])