<a href="https://colab.research.google.com/github/neelkothimbire/PyTorch/blob/main/Pytorch_NN_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##  Normal nn

In [ ]:
#create model class
import torch
import torch.nn as nn

class Model(nn.Module): #base class inherit form this class
  def __init__(self , num_features):
    super().__init__() #parent class ka constructor invoke karoge with help of super keyword
    self.linear=nn.Linear(num_features,1) #num_features = input , 1 = output
    self.sigmoid=nn.Sigmoid() #activation function

  def forward(self,features):
    out=self.linear(features) #calculating z
    out=self.sigmoid(out)  #calculating y_pred

    return out



In [ ]:
# create dataset

features=torch.rand(10,5)


#create model
model=Model(features.shape[1]) #object

#call model for forward class
model(features) #simple call as function because it a feature of pytoch #magic function



tensor([[0.5826],
        [0.5783],
        [0.5872],
        [0.5653],
        [0.4694],
        [0.5205],
        [0.5404],
        [0.5012],
        [0.5618],
        [0.5024]], grad_fn=<SigmoidBackward0>)

In [ ]:
#show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.1729, -0.3039, -0.2898,  0.0751,  0.4015]], requires_grad=True)

In [ ]:
#show bias
model.linear.bias

Parameter containing:
tensor([0.2395], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model,imput_size=(10,5))

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            6
├─Sigmoid: 1-2                           --
Total params: 6
Trainable params: 6
Non-trainable params: 0

## Adding hidden layer
input layer 5

hidden layer 3 relu


In [ ]:
#create model class
import torch
import torch.nn as nn

class Model(nn.Module): #base class inherit form this class
  def __init__(self , num_features):
    super().__init__() #parent class ka constructor invoke karoge with help of super keyword
    self.linear1=nn.Linear(num_features,3) #num_features = input , 3 = output
    self.relu=nn.ReLU() #hidden layer
    self.linear2=nn.Linear(3,1)  #input 3 from linear function
    self.sigmoid=nn.Sigmoid() #activation function

  def forward(self,features):
    out=self.linear1(features) #calculating z
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)  #calculating y_pred

    return out



In [ ]:
# create dataset

features=torch.rand(10,5)


#create model
model=Model(features.shape[1]) #object

#call model for forward class
model(features) #simple call as function because it a feature of pytoch #magic function



tensor([[0.6498],
        [0.6308],
        [0.6626],
        [0.6884],
        [0.6379],
        [0.6197],
        [0.6439],
        [0.6918],
        [0.6873],
        [0.6681]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear1.weight

Parameter containing:
tensor([[ 0.3186, -0.2236,  0.3930,  0.3642,  0.2632],
        [-0.0553, -0.3836,  0.3155, -0.2752,  0.4233],
        [-0.2586, -0.2445, -0.4068, -0.4278,  0.2550]], requires_grad=True)

In [ ]:
model.linear2.weight

Parameter containing:
tensor([[ 0.5585,  0.2172, -0.1255]], requires_grad=True)

In [ ]:
model.linear1.bias

Parameter containing:
tensor([-0.3564,  0.2459,  0.0593], requires_grad=True)

In [ ]:
from torchinfo import summary
summary(model,imput_size=(10,5))

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            18
├─ReLU: 1-2                              --
├─Linear: 1-3                            4
├─Sigmoid: 1-4                           --
Total params: 22
Trainable params: 22
Non-trainable params: 0

##using sequential container

In [ ]:
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__ (self,num_features):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out=self.network(features)

    return out

In [ ]:
features=torch.rand(10,5)

In [ ]:
model=Model(features.shape[1])

In [ ]:
model(features)

tensor([[0.4937],
        [0.4985],
        [0.5033],
        [0.4930],
        [0.4930],
        [0.5147],
        [0.4930],
        [0.5065],
        [0.5050],
        [0.4930]], grad_fn=<SigmoidBackward0>)

# Training NN pipeline using pytorch nn module

## Basic

In [ ]:

import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:

df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:

df.shape

(569, 33)

In [ ]:

df.drop(columns=['id','Unnamed: 32'] , inplace=True)


In [ ]:

df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:] , df.iloc[:,0] ,test_size=0.2)

In [ ]:

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)


In [ ]:

X_train

array([[ 0.56669724,  0.29370727,  0.57260375, ...,  0.6335625 ,
         0.34229711, -0.12371178],
       [-0.67053742, -0.10914916, -0.70007923, ..., -0.70744464,
        -0.58771062, -0.23507474],
       [ 0.23993323, -0.68953554,  0.27582008, ...,  0.39294218,
        -0.49765706, -0.35020359],
       ...,
       [-0.27115919, -0.54614596, -0.3335595 , ..., -0.29162264,
        -0.63519341, -0.43412929],
       [ 2.90152381,  0.4962735 ,  2.94849488, ...,  1.97502079,
         0.43071334,  0.66766456],
       [ 1.4827536 ,  2.12818345,  1.65513435, ...,  1.17195047,
        -0.12434409,  0.87156099]])

In [ ]:

y_train


328    M
211    B
128    B
379    M
280    M
      ..
393    M
221    B
224    B
521    M
256    M
Name: diagnosis, Length: 455, dtype: object

In [ ]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.fit_transform(y_test)

In [ ]:
y_train

array([1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,

In [ ]:
X_train_tensors=torch.from_numpy(X_train)
X_test_tensors=torch.from_numpy(X_test)
y_train_tensors=torch.from_numpy(y_train)
y_test_tensors=torch.from_numpy(y_test)

In [ ]:
X_train_tensors.shape

torch.Size([455, 30])

In [ ]:
y_train_tensors.shape

torch.Size([455])

In [ ]:
X_train_tensors = X_train_tensors.float()
y_train_tensors = y_train_tensors.float()
y_test_tensors=y_test_tensors.float()
X_test_tensors=X_test_tensors.float()

In [ ]:
import torch
import torch.nn as nn

class mySimpleNN(nn.Module):  # ✓ Must inherit from torch.nn.Module
    def __init__(self, num_features):
        super().__init__()  # ✓ Initialize base class
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

    def loss_function(self, y_pred, y_true):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        loss = -(y_true * torch.log(y_pred) + (1 - y_true) * torch.log(1 - y_pred)).mean()
        return loss


In [ ]:

learning_rate=0.1
epochs=25

In [ ]:
# Define model
model = mySimpleNN(X_train_tensors.shape[1])

# Note: model parameters will require gradients
learning_rate = 0.01
epochs = 100

for epoch in range(epochs):
    # Forward pass
    y_pred = model(X_train_tensors)

    # Compute loss
    loss = model.loss_function(y_pred, y_train_tensors)

    # Backward pass
    loss.backward()

    # Update weights manually (not recommended in practice)
    with torch.no_grad():
        model.linear.weight -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad

    # Zero gradients
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()

    # Print loss
    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')


Epoch: 1, Loss: 0.7283061146736145
Epoch: 2, Loss: 0.7275122404098511
Epoch: 3, Loss: 0.7267462611198425
Epoch: 4, Loss: 0.7260069847106934
Epoch: 5, Loss: 0.7252930402755737
Epoch: 6, Loss: 0.7246032953262329
Epoch: 7, Loss: 0.7239365577697754
Epoch: 8, Loss: 0.7232916951179504
Epoch: 9, Loss: 0.7226676940917969
Epoch: 10, Loss: 0.7220633625984192
Epoch: 11, Loss: 0.7214781045913696
Epoch: 12, Loss: 0.7209106683731079
Epoch: 13, Loss: 0.7203602194786072
Epoch: 14, Loss: 0.7198261618614197
Epoch: 15, Loss: 0.7193076014518738
Epoch: 16, Loss: 0.7188037633895874
Epoch: 17, Loss: 0.718313992023468
Epoch: 18, Loss: 0.7178375720977783
Epoch: 19, Loss: 0.717373788356781
Epoch: 20, Loss: 0.7169223427772522
Epoch: 21, Loss: 0.716482400894165
Epoch: 22, Loss: 0.7160534858703613
Epoch: 23, Loss: 0.7156351208686829
Epoch: 24, Loss: 0.7152268290519714
Epoch: 25, Loss: 0.7148280739784241
Epoch: 26, Loss: 0.7144383788108826
Epoch: 27, Loss: 0.7140575647354126
Epoch: 28, Loss: 0.7136850357055664
Epoc

In [ ]:
model.linear.weight

Parameter containing:
tensor([[-0.0675, -0.1489, -0.0565, -0.0097, -0.1476,  0.0035,  0.0072,  0.1343,
         -0.1294,  0.1213, -0.0008, -0.0212, -0.1334, -0.0834, -0.0280, -0.0574,
         -0.0699,  0.1291, -0.0215,  0.0807,  0.1909,  0.1132, -0.0994, -0.0027,
         -0.0531, -0.0596,  0.1372,  0.1160, -0.0585,  0.0114]],
       requires_grad=True)

In [ ]:
with torch.no_grad():
  y_pred=model.forward(X_test_tensors)
  y_pred = (y_pred >0.5).float()
  accuracy = (y_pred == y_test_tensors).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5247768759727478


## Using Built in loss function

In [ ]:
import torch
import torch.nn as nn

class mySimpleNN(nn.Module):  # ✓ Must inherit from torch.nn.Module
    def __init__(self, num_features):
        super().__init__()  # ✓ Initialize base class
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out




In [ ]:
learning_rate=0.1
epochs=25

In [ ]:
##here
loss_function=nn.BCELoss()

In [ ]:
# Define model
model = mySimpleNN(X_train_tensors.shape[1])

# Note: model parameters will require gradients
learning_rate = 0.01
epochs = 100

for epoch in range(epochs):
    # Forward pass
    y_pred = model(X_train_tensors)

    # Compute loss
    loss =loss_function(y_pred, y_train_tensors.view(-1,1)) #using reshpe

    # Backward pass
    loss.backward()

    # Update weights manually (not recommended in practice)
    with torch.no_grad():
        model.linear.weight -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad

    # Zero gradients
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()

    # Print loss
    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')


Epoch: 1, Loss: 0.6276895999908447
Epoch: 2, Loss: 0.6127029061317444
Epoch: 3, Loss: 0.5985679030418396
Epoch: 4, Loss: 0.5852209329605103
Epoch: 5, Loss: 0.5726025700569153
Epoch: 6, Loss: 0.5606584548950195
Epoch: 7, Loss: 0.549338698387146
Epoch: 8, Loss: 0.5385971665382385
Epoch: 9, Loss: 0.5283920764923096
Epoch: 10, Loss: 0.5186849236488342
Epoch: 11, Loss: 0.5094406604766846
Epoch: 12, Loss: 0.5006271004676819
Epoch: 13, Loss: 0.49221503734588623
Epoch: 14, Loss: 0.4841773808002472
Epoch: 15, Loss: 0.47648951411247253
Epoch: 16, Loss: 0.46912890672683716
Epoch: 17, Loss: 0.46207472681999207
Epoch: 18, Loss: 0.45530804991722107
Epoch: 19, Loss: 0.44881105422973633
Epoch: 20, Loss: 0.44256773591041565
Epoch: 21, Loss: 0.436563104391098
Epoch: 22, Loss: 0.43078336119651794
Epoch: 23, Loss: 0.42521578073501587
Epoch: 24, Loss: 0.4198484718799591
Epoch: 25, Loss: 0.414670467376709
Epoch: 26, Loss: 0.40967172384262085
Epoch: 27, Loss: 0.4048425555229187
Epoch: 28, Loss: 0.40017437934

In [ ]:
with torch.no_grad():
  y_pred=model.forward(X_test_tensors)
  y_pred = (y_pred >0.5).float()
  accuracy = (y_pred == y_test_tensors).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5495536923408508


## Optimizer

In [ ]:
import torch
import torch.nn as nn

class mySimpleNN(nn.Module):  # ✓ Must inherit from torch.nn.Module
    def __init__(self, num_features):
        super().__init__()  # ✓ Initialize base class
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out




In [ ]:
learning_rate=0.1
epochs=25

In [ ]:
##here
loss_function=nn.BCELoss()

In [ ]:
# Define model
model = mySimpleNN(X_train_tensors.shape[1])


#opitmizer

opitmizer=torch.optim.SGD(model.parameters() ,lr=learning_rate)
#model.parameters retrives an iterator over all the trainable paramters (weights and bias)

for epoch in range(epochs):
    # Forward pass
    y_pred = model(X_train_tensors)

    # Compute loss
    loss =loss_function(y_pred, y_train_tensors.view(-1,1)) #using reshpe

    #clear graidents
    opitmizer.zero_grad()

    # Backward pass
    loss.backward()

    # Update weights
    opitmizer.step()


    # Print loss
    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')


Epoch: 1, Loss: 0.6389182209968567
Epoch: 2, Loss: 0.4869358539581299
Epoch: 3, Loss: 0.40682581067085266
Epoch: 4, Loss: 0.35737869143486023
Epoch: 5, Loss: 0.32332831621170044
Epoch: 6, Loss: 0.29814690351486206
Epoch: 7, Loss: 0.27858784794807434
Epoch: 8, Loss: 0.26284515857696533
Epoch: 9, Loss: 0.24982814490795135
Epoch: 10, Loss: 0.238835871219635
Epoch: 11, Loss: 0.22939538955688477
Epoch: 12, Loss: 0.22117480635643005
Epoch: 13, Loss: 0.21393372118473053
Epoch: 14, Loss: 0.20749317109584808
Epoch: 15, Loss: 0.20171695947647095
Epoch: 16, Loss: 0.196499302983284
Epoch: 17, Loss: 0.19175657629966736
Epoch: 18, Loss: 0.18742184340953827
Epoch: 19, Loss: 0.1834406852722168
Epoch: 20, Loss: 0.17976832389831543
Epoch: 21, Loss: 0.17636755108833313
Epoch: 22, Loss: 0.17320717871189117
Epoch: 23, Loss: 0.17026083171367645
Epoch: 24, Loss: 0.16750594973564148
Epoch: 25, Loss: 0.16492317616939545


In [ ]:
with torch.no_grad():
  y_pred=model.forward(X_test_tensors)
  y_pred = (y_pred >0.5).float()
  accuracy = (y_pred == y_test_tensors).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5530932545661926


# Final Optimize code of pipeline using nn module

In [ ]:

import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:

df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:

df.shape

(569, 33)

In [ ]:

df.drop(columns=['id','Unnamed: 32'] , inplace=True)


In [ ]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:] , df.iloc[:,0] ,test_size=0.2)

In [ ]:

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [ ]:

encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.fit_transform(y_test)

In [ ]:

X_train_tensors=torch.from_numpy(X_train)
X_test_tensors=torch.from_numpy(X_test)
y_train_tensors=torch.from_numpy(y_train)
y_test_tensors=torch.from_numpy(y_test)


X_train_tensors = X_train_tensors.float()
y_train_tensors = y_train_tensors.float()
y_test_tensors=y_test_tensors.float()
X_test_tensors=X_test_tensors.float()

In [ ]:
import torch
import torch.nn as nn

class mySimpleNN(nn.Module):  # ✓ Must inherit from torch.nn.Module
    def __init__(self, num_features):
        super().__init__()  # ✓ Initialize base class
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [ ]:
learning_rate=0.1
epochs=25

In [ ]:
loss_function=nn.BCELoss()

In [ ]:
# Define model
model = mySimpleNN(X_train_tensors.shape[1])


#opitmizer

opitmizer=torch.optim.SGD(model.parameters() ,lr=learning_rate)
#model.parameters retrives an iterator over all the trainable paramters (weights and bias)

for epoch in range(epochs):
    # Forward pass
    y_pred = model(X_train_tensors)

    # Compute loss
    loss =loss_function(y_pred, y_train_tensors.view(-1,1)) #using reshpe

    #clear graidents
    opitmizer.zero_grad()

    # Backward pass
    loss.backward()

    # Update weights
    opitmizer.step()


    # Print loss
    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')


Epoch: 1, Loss: 0.6934235692024231
Epoch: 2, Loss: 0.5319297909736633
Epoch: 3, Loss: 0.4458215534687042
Epoch: 4, Loss: 0.39199167490005493
Epoch: 5, Loss: 0.354461669921875
Epoch: 6, Loss: 0.3264034390449524
Epoch: 7, Loss: 0.3044096827507019
Epoch: 8, Loss: 0.28657233715057373
Epoch: 9, Loss: 0.2717299461364746
Epoch: 10, Loss: 0.25912994146347046
Epoch: 11, Loss: 0.24826039373874664
Epoch: 12, Loss: 0.2387596219778061
Epoch: 13, Loss: 0.2303636223077774
Epoch: 14, Loss: 0.22287490963935852
Epoch: 15, Loss: 0.21614216268062592
Epoch: 16, Loss: 0.21004728972911835
Epoch: 17, Loss: 0.2044965922832489
Epoch: 18, Loss: 0.1994147151708603
Epoch: 19, Loss: 0.19474008679389954
Epoch: 20, Loss: 0.19042201340198517
Epoch: 21, Loss: 0.18641817569732666
Epoch: 22, Loss: 0.1826930046081543
Epoch: 23, Loss: 0.17921634018421173
Epoch: 24, Loss: 0.1759624481201172
Epoch: 25, Loss: 0.17290911078453064


In [ ]:
with torch.no_grad():
  y_pred=model.forward(X_test_tensors)
  y_pred = (y_pred >0.5).float()
  accuracy = (y_pred == y_test_tensors).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5215451121330261
